spring:
  liquibase:
    change-log: classpath:/migration/master-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud-config1
    username: postgres
    password: linh2002
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT prop_key, value_config FROM data_cloud WHERE application=? AND profile_client=? AND label=?
          order: 0
  jpa:
    show-sql: true
server:
  port: 8888